# Generated by Django 4.0.3 on 2023-02-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_user_events_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('event_fee', models.IntegerField()),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.typeofevent')),
            ],
        ),
    ]
