# Generated by Django 4.0.3 on 2023-02-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_typeofevent_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_cordinator1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_cordinator2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_cordinator3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_cordinator4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_prize_money',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_runner_prize_money',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='team_size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
