# Generated by Django 4.0.3 on 2023-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_user_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
    ]
