# Generated by Django 4.0.3 on 2023-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_poster',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
