# Generated by Django 4.0.3 on 2023-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_events_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='checksum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
