# Generated by Django 4.0.3 on 2023-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_registrations_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
