# Generated by Django 4.0.3 on 2023-02-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_registrations_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='payment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
