# Generated by Django 4.0.3 on 2023-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_registrations_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
