# Generated by Django 4.0.3 on 2023-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_user_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events_registered',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
