# Generated by Django 4.0.3 on 2023-03-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_registrations_first_name_registrations_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='event_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
